language: python
git:
  depth: false
jobs:
  include:
    - name: "Python 3.8"
      os: linux
      dist: focal
      python: 3.8
script:
- chmod +x .build.sh
- ./.build.sh
after_success:
- chmod +x .deploy.sh
- ./.deploy.sh